### ISSUE TITLE
pentaho-platform-assembly build error.

### ISSUE THREAD

**Issue by shuLhan** [pentaho/pentaho-platform#2096]
Version: master branch.

Running assembly.xml with ant target "clean-all, resolve" result in,

```
[ivy:resolve]   found pentaho#pentaho-user-console-package;TRUNK-SNAPSHOT in pentaho-mvn
[ivy:resolve] :: problems summary ::
[ivy:resolve] :::: ERRORS
[ivy:resolve]       pentaho-mvn: bad revision found in http://ivy-nexus.pentaho.org/content/groups/omni/org/jvnet/staxex/stax-ex/1.0/stax-ex-1.0.pom: expected='1.0 found='working@bubu'
[ivy:resolve]       public-maven: bad revision found in http://ivy-nexus.pentaho.org/content/groups/omni/org/jvnet/staxex/stax-ex/1.0/stax-ex-1.0.pom: expected='1.0 found='working@bubu'
[ivy:resolve]   impossible to get artifacts when data has not been loaded. IvyNode = org.apache.poi#poi;3.9
[ivy:resolve] 
[ivy:resolve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

BUILD FAILED
/home/ms/git/pentaho.com/pentaho-platform/assembly/build-res/subfloor.xml:740: impossible to resolve dependencies:
java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = org.apache.poi#poi;3.9
```

Here is the full log: https://gist.github.com/shuLhan/cea7dc39400b1558e468

**Comment by vetrivel123** [comment]
---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |  566  |  293  |  289  |  131  ||  441  |  281  |
	---------------------------------------------------------------------
[ivy:resolve] :: problems summary ::
[ivy:resolve] :::: WARNINGS
[ivy:resolve] 		[NOT FOUND  ] pentaho-library#libbase;7.0-SNAPSHOT!libbase.jar(source) (2234ms)
[ivy:resolve] 	==== pentaho-ivy: tried
[ivy:resolve] 	==== pentaho-mvn: tried
[ivy:resolve] 	  http://nexus.pentaho.org/content/groups/omni/pentaho-library/libbase/7.0-SNAPSHOT/libbase-7.0-20160922.022144-696-sources.jar
[ivy:resolve] 	  http://nexus.pentaho.org/content/groups/omni/pentaho-library/libbase/7.0-SNAPSHOT/libbase-7.0-SNAPSHOT-sources.jar
[ivy:resolve] 		[NOT FOUND  ] pentaho-library#libformula;7.0-SNAPSHOT!libformula.jar(source) (2358ms)
[ivy:resolve] 	==== pentaho-ivy: tried
[ivy:resolve] 	==== pentaho-mvn: tried
[ivy:resolve] 	  http://nexus.pentaho.org/content/groups/omni/pentaho-library/libformula/7.0-SNAPSHOT/libformula-7.0-20160922.022709-675-sources.jar
[ivy:resolve] 	  http://nexus.pentaho.org/content/groups/omni/pentaho-library/libformula/7.0-SNAPSHOT/libformula-7.0-SNAPSHOT-sources.jar
[ivy:resolve] 		[NOT FOUND  ] pentaho#pentaho-versionchecker;7.0-SNAPSHOT!pentaho-versionchecker.jar(source) (2386ms)
[ivy:resolve] 	==== pentaho-ivy: tried
[ivy:resolve] 	==== pentaho-mvn: tried
[ivy:resolve] 	  http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-versionchecker/7.0-SNAPSHOT/pentaho-versionchecker-7.0-20160922.022143-669-sources.jar
[ivy:resolve] 	  http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-versionchecker/7.0-SNAPSHOT/pentaho-versionchecker-7.0-SNAPSHOT-sources.jar
[ivy:resolve] 		[NOT FOUND  ] pentaho#pentaho-actionsequence-dom;7.0-SNAPSHOT!pentaho-actionsequence-dom.jar(source) (2539ms)
[ivy:resolve] 	==== pentaho-ivy: tried
[ivy:resolve] 	==== pentaho-mvn: tried
[ivy:resolve] 	  http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-actionsequence-dom/7.0-SNAPSHOT/pentaho-actionsequence-dom-7.0-20160922.031013-648-sources.jar
[ivy:resolve] 	  http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-actionsequence-dom/7.0-SNAPSHOT/pentaho-actionsequence-dom-7.0-SNAPSHOT-sources.jar
[ivy:resolve] 		[NOT FOUND  ] pentaho#pentaho-metadata;7.0-SNAPSHOT!pentaho-metadata.jar(source) (2339ms)
[ivy:resolve] 	==== pentaho-ivy: tried
[ivy:resolve] 	==== pentaho-mvn: tried
[ivy:resolve] 	  http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-metadata/7.0-SNAPSHOT/pentaho-metadata-7.0-20160922.041145-678-sources.jar
[ivy:resolve] 	  http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-metadata/7.0-SNAPSHOT/pentaho-metadata-7.0-SNAPSHOT-sources.jar
[ivy:resolve] 		[NOT FOUND  ] pentaho#pentaho-platform-api;7.0-SNAPSHOT!pentaho-platform-api.jar(source) (2506ms)
[ivy:resolve] 	==== pentaho-ivy: tried
[ivy:resolve] 	==== pentaho-mvn: tried
[ivy:resolve] 	  http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-platform-api/7.0-SNAPSHOT/pentaho-platform-api-7.0-20160922.052614-1107-sources.jar
[ivy:resolve] 	  http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-platform-api/7.0-SNAPSHOT/pentaho-platform-api-7.0-SNAPSHOT-sources.jar
[ivy:resolve] 		[NOT FOUND  ] pentaho#pentaho-platform-core;7.0-SNAPSHOT!pentaho-platform-core.jar(source) (3228ms)
[ivy:resolve] 	==== pentaho-ivy: tried
[ivy:resolve] 	==== pentaho-mvn: tried
[ivy:resolve] 	  http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-platform-core/7.0-SNAPSHOT/pentaho-platform-core-7.0-20160922.053130-1160-sources.jar
[ivy:resolve] 	  http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-platform-core/7.0-SNAPSHOT/pentaho-platform-core-7.0-SNAPSHOT-sources.jar
[ivy:resolve] 		[NOT FOUND  ] org.apache.jackrabbit#jackrabbit-jca;1.5.4!jackrabbit-jca.rar (0ms)
[ivy:resolve] 	==== pentaho-mvn: tried
[ivy:resolve] 	  http://nexus.pentaho.org/content/groups/omni/org/apache/jackrabbit/jackrabbit-jca/1.5.4/jackrabbit-jca-1.5.4.rar
[ivy:resolve] 		::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] 		::              FAILED DOWNLOADS            ::
[ivy:resolve] 		:: ^ see resolution messages for details  ^ ::
[ivy:resolve] 		::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] 		:: org.apache.jackrabbit#jackrabbit-jca;1.5.4!jackrabbit-jca.rar
[ivy:resolve] 		:: pentaho-library#libbase;7.0-SNAPSHOT!libbase.jar(source)
[ivy:resolve] 		:: pentaho#pentaho-metadata;7.0-SNAPSHOT!pentaho-metadata.jar(source)
[ivy:resolve] 		:: pentaho-library#libformula;7.0-SNAPSHOT!libformula.jar(source)
[ivy:resolve] 		:: pentaho#pentaho-versionchecker;7.0-SNAPSHOT!pentaho-versionchecker.jar(source)
[ivy:resolve] 		:: pentaho#pentaho-actionsequence-dom;7.0-SNAPSHOT!pentaho-actionsequence-dom.jar(source)
[ivy:resolve] 		:: pentaho#pentaho-platform-api;7.0-SNAPSHOT!pentaho-platform-api.jar(source)
[ivy:resolve] 		:: pentaho#pentaho-platform-core;7.0-SNAPSHOT!pentaho-platform-core.jar(source)
[ivy:resolve] 		::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] 
[ivy:resolve] :::: ERRORS
[ivy:resolve] 	unknown resolver default
[ivy:resolve] 
[ivy:resolve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

I'm getting this error while using the Ant build in eclipse while building pentaho-platform-master 7.x
 any changes to be done or the files to be updated?

Thanks in advance...anyone suggest me where the build is going wrong...
