### ISSUE TITLE
how to debug Pentaho with IntelliJ IDEA?

### ISSUE THREAD

**Issue by tzq668766** [pentaho/pentaho-platform#2682]
I didn't find any articles tell me how to debug on IntelliJ IDEA! Please tell me how?

**Comment by pamval** [comment]
It's standard java remote debugging. 

if you start the ba server with the start-pentaho-debug script, that will open the 8044 port for debugging purposes.

In Intellij, create a remote debug configuration and specify host and port. And that's it.

**Comment by tzq668766** [comment]
Thanks a lot,pamval!
