### ISSUE TITLE
Resolve Error on building pentaho platform 

### ISSUE THREAD

**Issue by vetrivel123** [pentaho/pentaho-platform#3096]
---

```
|                  |            modules            ||   artifacts   |
|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
---------------------------------------------------------------------
|      default     |  566  |  293  |  289  |  131  ||  441  |  281  |
---------------------------------------------------------------------
```

[ivy:resolve] :: problems summary ::
[ivy:resolve] :::: WARNINGS
[ivy:resolve]       [NOT FOUND  ] pentaho-library#libbase;7.0-SNAPSHOT!libbase.jar(source) (2234ms)
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://nexus.pentaho.org/content/groups/omni/pentaho-library/libbase/7.0-SNAPSHOT/libbase-7.0-20160922.022144-696-sources.jar
[ivy:resolve]     http://nexus.pentaho.org/content/groups/omni/pentaho-library/libbase/7.0-SNAPSHOT/libbase-7.0-SNAPSHOT-sources.jar
[ivy:resolve]       [NOT FOUND  ] pentaho-library#libformula;7.0-SNAPSHOT!libformula.jar(source) (2358ms)
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://nexus.pentaho.org/content/groups/omni/pentaho-library/libformula/7.0-SNAPSHOT/libformula-7.0-20160922.022709-675-sources.jar
[ivy:resolve]     http://nexus.pentaho.org/content/groups/omni/pentaho-library/libformula/7.0-SNAPSHOT/libformula-7.0-SNAPSHOT-sources.jar
[ivy:resolve]       [NOT FOUND  ] pentaho#pentaho-versionchecker;7.0-SNAPSHOT!pentaho-versionchecker.jar(source) (2386ms)
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-versionchecker/7.0-SNAPSHOT/pentaho-versionchecker-7.0-20160922.022143-669-sources.jar
[ivy:resolve]     http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-versionchecker/7.0-SNAPSHOT/pentaho-versionchecker-7.0-SNAPSHOT-sources.jar
[ivy:resolve]       [NOT FOUND  ] pentaho#pentaho-actionsequence-dom;7.0-SNAPSHOT!pentaho-actionsequence-dom.jar(source) (2539ms)
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-actionsequence-dom/7.0-SNAPSHOT/pentaho-actionsequence-dom-7.0-20160922.031013-648-sources.jar
[ivy:resolve]     http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-actionsequence-dom/7.0-SNAPSHOT/pentaho-actionsequence-dom-7.0-SNAPSHOT-sources.jar
[ivy:resolve]       [NOT FOUND  ] pentaho#pentaho-metadata;7.0-SNAPSHOT!pentaho-metadata.jar(source) (2339ms)
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-metadata/7.0-SNAPSHOT/pentaho-metadata-7.0-20160922.041145-678-sources.jar
[ivy:resolve]     http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-metadata/7.0-SNAPSHOT/pentaho-metadata-7.0-SNAPSHOT-sources.jar
[ivy:resolve]       [NOT FOUND  ] pentaho#pentaho-platform-api;7.0-SNAPSHOT!pentaho-platform-api.jar(source) (2506ms)
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-platform-api/7.0-SNAPSHOT/pentaho-platform-api-7.0-20160922.052614-1107-sources.jar
[ivy:resolve]     http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-platform-api/7.0-SNAPSHOT/pentaho-platform-api-7.0-SNAPSHOT-sources.jar
[ivy:resolve]       [NOT FOUND  ] pentaho#pentaho-platform-core;7.0-SNAPSHOT!pentaho-platform-core.jar(source) (3228ms)
[ivy:resolve]   ==== pentaho-ivy: tried
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-platform-core/7.0-SNAPSHOT/pentaho-platform-core-7.0-20160922.053130-1160-sources.jar
[ivy:resolve]     http://nexus.pentaho.org/content/groups/omni/pentaho/pentaho-platform-core/7.0-SNAPSHOT/pentaho-platform-core-7.0-SNAPSHOT-sources.jar
[ivy:resolve]       [NOT FOUND  ] org.apache.jackrabbit#jackrabbit-jca;1.5.4!jackrabbit-jca.rar (0ms)
[ivy:resolve]   ==== pentaho-mvn: tried
[ivy:resolve]     http://nexus.pentaho.org/content/groups/omni/org/apache/jackrabbit/jackrabbit-jca/1.5.4/jackrabbit-jca-1.5.4.rar
[ivy:resolve]       ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]       ::              FAILED DOWNLOADS            ::
[ivy:resolve]       :: ^ see resolution messages for details  ^ ::
[ivy:resolve]       ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]       :: org.apache.jackrabbit#jackrabbit-jca;1.5.4!jackrabbit-jca.rar
[ivy:resolve]       :: pentaho-library#libbase;7.0-SNAPSHOT!libbase.jar(source)
[ivy:resolve]       :: pentaho#pentaho-metadata;7.0-SNAPSHOT!pentaho-metadata.jar(source)
[ivy:resolve]       :: pentaho-library#libformula;7.0-SNAPSHOT!libformula.jar(source)
[ivy:resolve]       :: pentaho#pentaho-versionchecker;7.0-SNAPSHOT!pentaho-versionchecker.jar(source)
[ivy:resolve]       :: pentaho#pentaho-actionsequence-dom;7.0-SNAPSHOT!pentaho-actionsequence-dom.jar(source)
[ivy:resolve]       :: pentaho#pentaho-platform-api;7.0-SNAPSHOT!pentaho-platform-api.jar(source)
[ivy:resolve]       :: pentaho#pentaho-platform-core;7.0-SNAPSHOT!pentaho-platform-core.jar(source)
[ivy:resolve]       ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] 
[ivy:resolve] :::: ERRORS
[ivy:resolve]   unknown resolver default
[ivy:resolve] 
[ivy:resolve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

BUILD FAILED
F:\git-hub-pentaho\pentaho-platform\assembly\build-res\subfloor.xml:892: impossible to resolve dependencies:
    resolve failed - see output for details

Can any one suggest, how to fix this build issue...

**Comment by dkincade** [comment]
This has all been converted over to maven for the master branch. Please reopen an issue if you find you still have problems trying to resolve and compile the source code (and please read the readme on this project as it defines the setup needed to work correctly with maven).

**Comment by hieplq** [comment]
I try with source code download from release 7.1.0.5-R and 8.0.0.0-R
https://github.com/pentaho/pentaho-platform/releases/tag/7.1.0.5-R
https://github.com/pentaho/pentaho-platform/releases/tag/8.0.0.0-R

my server is google cloud centos 7 up to date.
i already setup environment like readme also this blog http://pedroalves-bi.blogspot.com/2017/04/building-pentaho-platform-from-source.html

but i got bellow error

`[ERROR] Failed to execute goal on project pentaho-platform-extensions: Could not resolve dependencies for project pentaho:pentaho-platform-extensions:jar:8.0.0.0-1: The following artifacts could not be resolved: org.eclipse.swt:org.eclipse.swt.gtk.linux.x86_64:jar:4.6, org.syslog4j:syslog4j:jar:0.9.46: Could not find artifact org.eclipse.swt:org.eclipse.swt.gtk.linux.x86_64:jar:4.6 in pentaho.resolve.repo (http://nexus.pentaho.org/content/groups/omni) -> [Help 1]`

actual i can't find out org.eclipse.swt:org.eclipse.swt.gtk.linux version 4.6 on maven repository

**Comment by lgrill-pentaho** [comment]
I was able to replicate this issue.
Tried removing the local cache of the swt items from our public artifact repository and resynchronized with the internal repository. After this I was able to finish a 8.0.0.0-1 build of the platform.
Please retry. You might need to do `mvn -U ` to force updates (might want to limit this to the extensions module).

**Comment by hieplq** [comment]
great. build success after delete ~/.m2/repository to re-create.
thanks in advance.
