### ISSUE TITLE
Pentaho j_spring_security_check Internal Server Error

### ISSUE THREAD

**Issue by rtUsmanKhan** [pentaho/pentaho-platform#3173]
Hi,
When i close browser or shutdown my PC it gives me "Pentaho j_spring_security_check Internal Server Error" in Enterprise Edition. After fresh installation this error is resolved but same error arises when i restart my PC.
Please help

**Comment by matthewtckr** [comment]
If you are a Pentaho customer, please contact Customer Support for assistance. Otherwise use http://forums.pentaho.com for asking questions. JIRA is for logging bugs and enhancement requests.
