### ISSUE TITLE
Building Pentaho-Platform for BA Server

### ISSUE THREAD

**Issue by rtUsmanKhan** [pentaho/pentaho-platform#3290]
Hi,
After clone when i try to build complete project it gives me 100 errors approx.  
pentaho-platform/user-console/source/org/pentaho/mantle/client/events/SolutionBrowserCloseEventHandler.java
Error:(20, 35) java: package com.google.gwt.event.shared does not exist  and others which requires some packages as well.  Why this is so?

**Comment by hmassad** [comment]
@rtUsmanKhan Your maven configuration is incorrect (/.m2/settings.xml), please check https://github.com/pentaho/pentaho-platform#how-to-build
