### ISSUE TITLE
How to build pentaho-platform with Intellij Idea 

### ISSUE THREAD

**Issue by NAakshay** [pentaho/pentaho-platform#3473]
I cloned the project from repository and i don't know how build pentaho-platform with intellij-idea 

getting this error : 

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for pentaho:pentaho-platform-ce-parent:7.1-SNAPSHOT: Could not find artifact org.pentaho:pentaho-ce-jar-parent-pom:pom:7.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project pentaho:pentaho-platform-ce-parent:7.1-SNAPSHOT (E:\prepro\pentaho\git\pentaho-platform\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for pentaho:pentaho-platform-ce-parent:7.1-SNAPSHOT: Could not find artifact org.pentaho:pentaho-ce-jar-parent-pom:pom:7.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Process finished with exit code 1

**Comment by hmassad** [comment]
Since April 8, https://github.com/pentaho/pentaho-platform explains how

**Comment by NAakshay** [comment]
Thank you @hmassad
