### ISSUE TITLE
The detail about api/userroledao/updatePassword

### ISSUE THREAD

**Issue by guoying9464** [pentaho/pentaho-platform#3654]
Hi, I notice that the userroledao/updatePassword api has been updated by the documentation 7.1,  but I want to know the detail about the userroledao/updatePassword api, where can I find that

**Comment by rmansoor** [comment]
We do not have any documentation on the update password on our site. Any api that does not have documentation is not officially supported.

**Comment by dile2011** [comment]
cannot add multiple param on Parameters panel

**Comment by dkincade** [comment]
Pentaho does not use github for issues tracking. Please create a JIRA issue using http://jira.pentaho.com if you feel there is a product defect or a needed Improvement.
